name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  # Stage 1: Unit Tests (Parallel)
  unit-tests-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: api/package-lock.json

      - name: Install API dependencies
        run: npm ci
        working-directory: ./api

      - name: Check API TypeScript compilation
        run: npx tsc --noEmit
        working-directory: ./api

      - name: Run API unit tests
        run: npm run test:unit
        working-directory: ./api

  unit-tests-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: webapp/package-lock.json

      - name: Install UI dependencies
        run: npm ci
        working-directory: ./webapp

      - name: Check UI TypeScript compilation
        run: npx tsc --noEmit
        working-directory: ./webapp

      - name: Build UI
        run: npm run build
        working-directory: ./webapp

      - name: Run UI unit tests
        run: npm test
        working-directory: ./webapp

  # Stage 2: API Integration + E2E Tests
  integration-and-e2e-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests-api, unit-tests-ui]
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: platform_user
          POSTGRES_PASSWORD: platform_password
          POSTGRES_DB: platform_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: api/package-lock.json

      - name: Install API dependencies
        run: npm ci
        working-directory: ./api

      - name: Install UI dependencies
        run: npm ci
        working-directory: ./webapp

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5433 -U platform_user; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Clear database
        run: |
          echo "Clearing database..."
          PGPASSWORD=platform_password psql -h localhost -p 5433 -U platform_user -d platform_db -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public; GRANT ALL ON SCHEMA public TO platform_user; GRANT ALL ON SCHEMA public TO public;"

      - name: Run database migrations
        run: |
          echo "Running database migrations..."
          cd api
          npm run migration:run
        env:
          NODE_ENV: test
          DB_HOST: localhost
          DB_PORT: 5433
          DB_USER: platform_user
          DB_PASSWORD: platform_password
          DB_NAME: platform_db

      - name: Build API
        run: npm run build
        working-directory: ./api

      - name: Build UI
        run: npm run build
        working-directory: ./webapp
        env:
          NODE_ENV: test

      - name: Start API server
        run: |
          cd api
          echo "Starting API server..."
          npm start &
          API_PID=$!
          echo "API server started with PID: $API_PID"
          sleep 5
          echo "Checking if API process is still running..."
          ps aux | grep node || echo "No node processes found"
          echo "Checking port 4001..."
          netstat -tlnp | grep :4001 || echo "Port 4001 not in use"
          sleep 5
        env:
          NODE_ENV: test
          DB_HOST: localhost
          DB_PORT: 5433
          DB_USER: platform_user
          DB_PASSWORD: platform_password
          DB_NAME: platform_db
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          JWT_SECRET: test-jwt-secret-key
          API_PORT: 4001
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}

      - name: Start UI server with nginx
        env:
          NODE_ENV: test
        run: |
          echo "Starting nginx for UI server..."
          # Copy built files to nginx directory
          sudo mkdir -p /usr/share/nginx/html
          sudo cp -r webapp/dist/* /usr/share/nginx/html/

          # Start nginx with the correct config path
          sudo nginx -c $(pwd)/docker/nginx.conf
          sleep 5
          echo "Nginx started for UI server"

      - name: Verify API server is running
        run: |
          echo "Checking if API server is responding..."
          curl -v http://localhost:4001/health || echo "Health endpoint not responding"
          curl -v http://localhost:4001/api/health || echo "API health endpoint not responding"
          TIMEOUT=15
          ELAPSED=0
          until curl -f http://localhost:4001/health; do
            echo "Waiting for API server... ($ELAPSED seconds)"
            sleep 2
            ELAPSED=$((ELAPSED+2))
            if [ $ELAPSED -ge $TIMEOUT ]; then
              echo "API server did not become ready within $TIMEOUT seconds."
              exit 1
            fi
          done
          echo "API server is ready!"

      - name: Verify UI server is running
        run: |
          until curl -f http://localhost:3000; do
            echo "Waiting for UI server..."
            sleep 2
          done
          echo "UI server is ready!"

      - name: Run API integration tests
        run: |
          echo "Running API integration tests..."
          cd api
          npm run test:integration
        env:
          NODE_ENV: test
          DB_HOST: localhost
          DB_PORT: 5433
          DB_USER: platform_user
          DB_PASSWORD: platform_password
          DB_NAME: platform_db
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          JWT_SECRET: test-jwt-secret-key
          API_PORT: 4001
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}

      - name: Test API login with test credentials
        run: |
          echo "Testing API login with test credentials..."
          # Test login endpoint
          response=$(curl -s -w "\n%{http_code}" -X POST http://localhost:4001/api/users/login \
            -H "Content-Type: application/json" \
            -d '{"email":"admin@platform.com","password":"admin123"}')

          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)

          echo "Login response status: $http_code"
          echo "Login response body: $body"

          if [ "$http_code" -eq 200 ]; then
            echo "✅ Login test passed!"
            # Extract token for further testing
            token=$(echo "$body" | grep -o '"token":"[^\"]*"' | cut -d'"' -f4)
            echo "Token extracted: ${token:0:20}..."

            # Test user profile endpoint
            profile_response=$(curl -s -w "\n%{http_code}" -X GET http://localhost:4001/api/users/profile \
              -H "Authorization: Bearer $token")

            profile_http_code=$(echo "$profile_response" | tail -n1)
            profile_body=$(echo "$profile_response" | head -n -1)

            echo "Profile response status: $profile_http_code"
            echo "Profile response body: $profile_body"

            if [ "$profile_http_code" -eq 200 ]; then
              echo "✅ Profile test passed!"
            else
              echo "❌ Profile test failed!"
              exit 1
            fi
          else
            echo "❌ Login test failed!"
            exit 1
          fi

      - name: Run E2E tests
        run: npm run test:e2e:local
        working-directory: ./webapp
        env:
          CYPRESS_baseUrl: http://localhost:3000
          CYPRESS_apiUrl: http://localhost:4001
          CYPRESS_testEmail: admin@platform.com
          CYPRESS_testPassword: admin123

      - name: Upload E2E screenshots (on failure)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: webapp/cypress/screenshots/
          if-no-files-found: ignore

      - name: Upload E2E videos (on failure)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: webapp/cypress/videos/
          if-no-files-found: ignore
